# Generated by Django 5.2.8 on 2025-11-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('experience_type', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('char_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '완성된 문단',
                'verbose_name_plural': '완성된 문단들',
                'ordering': ['-created_at'],
            },
        ),
    ]
